# Site settings
title: Vafliuko fotografija
description: Mano fotografuotos bei redaguotos nuotraukos
baseurl: "/photography" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/profile.php?id=100011541967315
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/neoskaras/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
